# Generated by Django 4.2.7 on 2025-08-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('semana', models.PositiveIntegerField()),
                ('total_visitantes', models.PositiveIntegerField(default=0)),
                ('total_sessoes', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('produtos_mais_vistos', models.JSONField(default=list)),
                ('termos_mais_buscados', models.JSONField(default=list)),
                ('total_carrinhos_criados', models.PositiveIntegerField(default=0)),
                ('total_carrinhos_abandonados', models.PositiveIntegerField(default=0)),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
                ('valor_total_pedidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tempo_medio_sessao', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório Semanal',
                'verbose_name_plural': 'Relatórios Semanais',
                'ordering': ['-ano', '-semana'],
                'unique_together': {('ano', 'semana')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visualizacoes', models.PositiveIntegerField(default=0)),
                ('visualizacoes_mes_atual', models.PositiveIntegerField(default=0)),
                ('visualizacoes_semana_atual', models.PositiveIntegerField(default=0)),
                ('total_adicoes_carrinho', models.PositiveIntegerField(default=0)),
                ('total_remocoes_carrinho', models.PositiveIntegerField(default=0)),
                ('total_vendas', models.PositiveIntegerField(default=0)),
                ('valor_total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxa_conversao_carrinho', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_conversao_venda', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Analytics do Produto',
                'verbose_name_plural': 'Analytics dos Produtos',
                'ordering': ['-total_visualizacoes'],
            },
        ),
        migrations.CreateModel(
            name='JornadaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('primeira_pagina', models.CharField(blank=True, max_length=200)),
                ('ultima_pagina', models.CharField(blank=True, max_length=200)),
                ('paginas_visitadas', models.PositiveIntegerField(default=0)),
                ('produtos_visualizados', models.PositiveIntegerField(default=0)),
                ('buscas_realizadas', models.PositiveIntegerField(default=0)),
                ('itens_carrinho', models.PositiveIntegerField(default=0)),
                ('tempo_total_sessao', models.PositiveIntegerField(default=0)),
                ('tempo_ate_primeira_busca', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_ate_carrinho', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_ate_checkout', models.PositiveIntegerField(blank=True, null=True)),
                ('converteu_pedido', models.BooleanField(default=False)),
                ('valor_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Jornada do Cliente',
                'verbose_name_plural': 'Jornadas do Cliente',
                'ordering': ['-iniciada_em'],
                'indexes': [models.Index(fields=['cliente', 'converteu_pedido'], name='analytics_j_cliente_3c58d2_idx'), models.Index(fields=['ativa', 'iniciada_em'], name='analytics_j_ativa_cf5507_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(choices=[('page_view', 'Visualização de Página'), ('product_view', 'Visualização de Produto'), ('search', 'Busca'), ('add_cart', 'Adicionar ao Carrinho'), ('remove_cart', 'Remover do Carrinho'), ('checkout_start', 'Início do Checkout'), ('checkout_complete', 'Checkout Finalizado'), ('price_unlock', 'Liberação de Preços'), ('filter_use', 'Uso de Filtro'), ('model_view', 'Visualização de Modelos')], max_length=30)),
                ('pagina', models.CharField(blank=True, max_length=200)),
                ('termo_busca', models.CharField(blank=True, max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='clientes.cliente')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Evento de Tracking',
                'verbose_name_plural': 'Eventos de Tracking',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['session_id', 'tipo_evento'], name='analytics_e_session_978c1e_idx'), models.Index(fields=['cliente', 'tipo_evento'], name='analytics_e_cliente_065133_idx'), models.Index(fields=['tipo_evento', 'criado_em'], name='analytics_e_tipo_ev_6a970d_idx'), models.Index(fields=['content_type', 'object_id'], name='analytics_e_content_3ec584_idx')],
            },
        ),
    ]
