# Generated by Django 4.2.7 on 2025-08-17 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('whatsapp_principal', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?55\\d{10,11}$', 'Formato: +5511999999999')])),
                ('whatsapp_secundario', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?55\\d{10,11}$', 'Formato: +5511999999999')])),
                ('precos_liberados', models.BooleanField(default=False)),
                ('data_liberacao_precos', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('total_pedidos', models.PositiveIntegerField(default=0)),
                ('valor_total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('paginas_visitadas', models.PositiveIntegerField(default=0)),
                ('produtos_visualizados', models.PositiveIntegerField(default=0)),
                ('tempo_total_minutos', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Sessão de Cliente',
                'verbose_name_plural': 'Sessões de Cliente',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['whatsapp_principal'], name='clientes_cl_whatsap_89c00b_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['precos_liberados', 'ativo'], name='clientes_cl_precos__960bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocliente',
            index=models.Index(fields=['session_id'], name='clientes_se_session_2885bc_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocliente',
            index=models.Index(fields=['cliente', 'ativa'], name='clientes_se_cliente_922535_idx'),
        ),
    ]
