# Generated by Django 4.2.7 on 2025-08-17 16:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone para UI', max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fabricantes/')),
                ('site', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MarcaCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/')),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca de Celular',
                'verbose_name_plural': 'Marcas de Celular',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='produtos.marcacelular')),
            ],
            options={
                'verbose_name': 'Modelo de Celular',
                'verbose_name_plural': 'Modelos de Celular',
                'ordering': ['marca__nome', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('caracteristicas', models.TextField(help_text='Características técnicas do produto')),
                ('tipo', models.CharField(choices=[('acessorio', 'Acessório'), ('capa_pelicula', 'Capa/Película')], max_length=20)),
                ('preco_atacado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_super_atacado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantidade_super_atacado', models.PositiveIntegerField(blank=True, help_text='Quantidade mínima para preço super atacado', null=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_3', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Peso em kg', max_digits=8, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.categoria')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.fabricante')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_atacado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_super_atacado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disponivel', models.BooleanField(default=True)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.modelocelular')),
                ('produto', models.ForeignKey(limit_choices_to={'tipo': 'capa_pelicula'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_precos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Preço por Modelo',
                'verbose_name_plural': 'Preços por Modelo',
                'indexes': [models.Index(fields=['produto', 'disponivel'], name='produtos_pr_produto_8c65a0_idx'), models.Index(fields=['modelo', 'disponivel'], name='produtos_pr_modelo__a28987_idx')],
                'unique_together': {('produto', 'modelo')},
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo', 'ativo'], name='produtos_pr_tipo_327f07_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'ativo'], name='produtos_pr_categor_409cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['fabricante', 'ativo'], name='produtos_pr_fabrica_8a9f5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelocelular',
            unique_together={('nome', 'marca')},
        ),
    ]
